site_name: Applied Statistic and Probability for Engineers
nav:
    - 前言: index.md
    - 第一章 统计思想和技术在工程实践中的关键作用: first.md
    
    



theme: 
    name: material
                                                                                                            
markdown_extensions:
    - footnotes
    - admonition
    - pymdownx.highlight:
        linenums: true
        linenums_style: pymdownx.inline
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.arithmatex:
        generic: true
    - attr_list
    - pymdownx.details
plugins:
    - search

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - js/math_equation_numbering.js
