site_name: Applied Statistic and Probability for Engineers
nav:
    - 前言: index.md
    - 第一章 统计思想和技术在工程实践中的关键作用: first.md
    - 第二章 概率: second.md
    - 第三章 离散随机变量及其概率分布: third.md
    
    



theme: 
    name: material
                                                                                                            
markdown_extensions:
    - footnotes
    - admonition
    - pymdownx.highlight:
        linenums: true
        linenums_style: pymdownx.inline
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.arithmatex:
        generic: true
    - attr_list
    - pymdownx.details
    - pymdownx.arithmatex:
        generic: true
plugins:
    - search

extra_javascript:
  - javascripts/mathjax_config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js